resources:
- controller.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: local-
# Adding additional prefix as a workaround, because the controller will fail running locally
# for Windows test, as it checks the same deployment name should not be deployed to enable Windows
# IPAM
images:
- digest: sha256:b6a951ea4127b100bae4657ed15d92061523565dcb5ada7bad64c63a18766380
  name: controller
  newName: 767520670908.dkr.ecr.us-west-2.amazonaws.com/dev
